#pragma once

enum SlotType
{
	ST_SHOVEL, ST_ATTACK, ST_BODY, ST_HEAD, ST_FEET, ST_BOMB, ST_FOOD_TOP, ST_FOOD_DOWN
};

enum PickableType
{
	PIT_COIN, PIT_DIAMOND, PIT_HEART
};




enum WeaponType // + 0
{
	WT_WEAPONAXE,
	WT_WEAPONAXE_TITANIUM,
	WT_BROADSWORD,
	WT_BROADSWORD_TITANIUM,
	WT_CAT,
	WT_CAT_TITANIUM,
	WT_CUTLASS,
	WT_CUTLASS_TITANIUM,
	WT_DAGGER,
	WT_DAGGER_JEWELED,
	WT_DAGGER_TITANIUM,
	WT_FLAIL,
	WT_FLAIL_TITANIUM,
	WT_HARP,
	WT_HARP_TITANIUM,
	WT_LONGSWORD,
	WT_LONGSWORD_TITANIUM,
	WT_RAPIER,
	WT_RAPIER_TITANIUM,
	WT_SPEAR,
	WT_SPEAR_TITANIUM,
	WT_STAFF,
	WT_STAFF_TITANIUM,
	WT_WARHAMMER,
	WT_WARHAMMER_TITANIUM,
	WT_WHIP,
	WT_WHIP_TITANIUM,
	WT_SIZE,
};

enum PickaxeType // + 100
{
	PT_PICKAXE,
	PT_SHOVEL,
	PT_SHOVEL_COURAGE,
	PT_SHOVEL_CRYSTAL,
	PT_SHOVEL_TITANIUM,
	PT_SIZE,
};

enum ArmorType // + 200
{
	AT_HEAD_HELMET, AT_HEAD_MINERSCAP,
	AT_BODY_CHAINMAIL, AT_BODY_LEATHERARMOR, AT_BODY_HEAVYPLATE, AT_BODY_PLATEMAIL,
	AT_FEET_BOOTSOFSTRENGTH, AT_FEET_HARGREAVES,
	AT_SIZE,
};

enum ConsomableType // + 300
{
	CT_APPLE, CT_CARROT, CT_CHEESE, CT_COOKIE, CT_DRUMSTICK, CT_HAM, CT_SIZE,
};