#pragma once

enum SlotType
{
	ST_SHOVEL, ST_ATTACK, ST_BODY, ST_HEAD, ST_FEET, ST_THROW, ST_BOMB, ST_FOOD_TOP, ST_FOOD_DOWN
};

enum WeaponType
{
	WT_BROADSWORD, WT_DAGGER, WT_SPEAR, WT_STAFF
};

enum PickaxeType
{
	PT_PICKAXE, PT_SHOVEL
};

enum ArmorType
{
	AT_HEAD_HELMET, AT_HEAD_MINERSCAP,
	AT_BODY_CHAINMAIL, AT_BODY_LEATHERARMOR, AT_BODY_HEAVYPLATE, AT_BODY_PLATEMAIL,
	AT_FEET_BOOTSOFSTRENGTH, AT_FEET_HARGREAVES
};

enum PickableType
{
	PIT_COIN, PIT_DIAMOND, PIT_HEART
};